### ISSUE TITLE
看缘之空（s站）第12集崩溃了，日志如下、

### ISSUE THREAD

**Issue by ietkd** [lanlinju/Animius#28]
App version: 1.3.0 (31)
Android version: 12 (SDK 31; build FBE-AN00 13.0.0.119(C11E40R5P1))
Device brand: Hinova
Device manufacturer: PTAC
Device name: ZN-MIZBD00-Q (FBE-AN00)
Device model: MIZ-BD00
WebView: Huawei WebView 14.0.2.309

java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1248)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1215)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1165)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1126)
	at Z3.y.a(Unknown Source:39)
	at Z3.g.a(Unknown Source:208)
	at W4.m.a(Unknown Source:40)
	at i0.e.c(Unknown Source:2)
	at D0.I.c(Unknown Source:51)
	at D0.e0.J0(Unknown Source:54)
	at B.l.d(Unknown Source:377)
	at c0.s.e(Unknown Source:113)
	at c0.t.a(Unknown Source:51)
	at c0.u.d(Unknown Source:123)
	at D0.m0.a(Unknown Source:2)
	at B.K.i(Unknown Source:1165)
	at A.w.a(Unknown Source:534)
	at S.N0.a(Unknown Source:1874)
	at o0.g.d(Unknown Source:34)
	at o0.b.e(Unknown Source:54)
	at E0.F0.k(Unknown Source:133)
	at E0.A.dispatchDraw(Unknown Source:98)
	at android.view.View.draw(View.java:23473)
	at android.view.View.updateDisplayListIfDirty(View.java:22304)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5715)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5438)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4415)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2874)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10697)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1165)
	at android.view.Choreographer.doFrame(Choreographer.java:1054)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1417)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9689)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)

**Comment by ietkd** [comment]
重启应用后看到同一个时间点再次崩溃

**Comment by ietkd** [comment]
换了girl站之后还是在同样的时间崩溃

App version: 1.3.0 (31)
Android version: 12 (SDK 31; build FBE-AN00 13.0.0.119(C11E40R5P1))
Device brand: Hinova
Device manufacturer: PTAC
Device name: ZN-MIZBD00-Q (FBE-AN00)
Device model: MIZ-BD00
WebView: Huawei WebView 14.0.2.309

java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1248)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1215)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1165)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1126)
	at Z3.y.a(Unknown Source:39)
	at Z3.g.a(Unknown Source:208)
	at W4.m.a(Unknown Source:40)
	at i0.e.c(Unknown Source:2)
	at D0.I.c(Unknown Source:51)
	at D0.e0.J0(Unknown Source:54)
	at B.l.d(Unknown Source:377)
	at c0.s.e(Unknown Source:113)
	at c0.t.a(Unknown Source:51)
	at c0.u.d(Unknown Source:123)
	at D0.m0.a(Unknown Source:2)
	at B.K.i(Unknown Source:1165)
	at A.w.a(Unknown Source:534)
	at S.N0.a(Unknown Source:1874)
	at o0.g.d(Unknown Source:34)
	at o0.b.e(Unknown Source:54)
	at E0.F0.k(Unknown Source:133)
	at E0.A.dispatchDraw(Unknown Source:98)
	at android.view.View.draw(View.java:23473)
	at android.view.View.updateDisplayListIfDirty(View.java:22304)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4802)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4775)
	at android.view.View.updateDisplayListIfDirty(View.java:22248)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5715)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5438)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4415)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2874)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10697)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1165)
	at android.view.Choreographer.doFrame(Choreographer.java:1054)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1417)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9689)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1211)
